/* https://projecteuler.net/problem=12
Highly divisible triangular number
Problem 12

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
 */

public class Problem012 {
    public static void main(String[] args){
        
        int n = 1; // start count of natural number here
        int t = n; // first triangle number
        int escalate = divisorCount(n);
        
        
        while(true){
            if( divisorCount(t) > 500 ){
                break;
            }
            n++;
            t += n;
            
            if(divisorCount(t) > escalate){
                escalate = divisorCount(t);
                System.out.printf("%d: Triangle number %d (of number %d) %n",escalate,t,n);
            }
        }
        
   
    private static int divisorCount(int n){
        int count = 0;
        for(int i = 1; i <= n; i++){
            if(n%i==0){
                count++;
            }
        }
        return count;
    }
    
    private static double divisorCount(double n){
        long count = 0; long m = (long)n;
        for(long i = 1; i <= n; i++){
            if(m%i==0){
                count++;
            }
        }
        return (double)count;
    }
    
    /* current code is gets the anwer but is running way to long.
       Us a modifeid version of the isPrime() code.
    
    run:
2: Triangle number 3 (of number 2) 
4: Triangle number 6 (of number 3) 
6: Triangle number 28 (of number 7) 
9: Triangle number 36 (of number 8) 
16: Triangle number 120 (of number 15) 
18: Triangle number 300 (of number 24) 
20: Triangle number 528 (of number 32) 
24: Triangle number 630 (of number 35) 
36: Triangle number 2016 (of number 63) 
40: Triangle number 3240 (of number 80) 
48: Triangle number 5460 (of number 104) 
90: Triangle number 25200 (of number 224) 
112: Triangle number 73920 (of number 384) 
128: Triangle number 157080 (of number 560) 
144: Triangle number 437580 (of number 935) 
162: Triangle number 749700 (of number 1224) 
168: Triangle number 1385280 (of number 1664) 
192: Triangle number 1493856 (of number 1728) 
240: Triangle number 2031120 (of number 2015) 
320: Triangle number 2162160 (of number 2079) 
480: Triangle number 17907120 (of number 5984) 
576: Triangle number 76576500 (of number 12375) 
Exception in thread "main" java.lang.RuntimeException: Uncompilable source code - illegal start of expression
	at Problem012.main(Problem012.java:46)
/home/radiancekfx/.cache/netbeans/8.1/executor-snippets/run.xml:53: Java returned: 1
BUILD FAILED (total time: 52 minutes 36 seconds)
    
    */
}
